### ISSUE TITLE
problem of python ./alma.py

### ISSUE THREAD

**Issue by wuwuqaz** [sollan/alma#19]
Hi,
When I try to operate alma.py, it showed the error below. Do you know how to solve it? T\Are there any other information that I can provide for you to better understand this problem? 
Thank you so much for your help in advance.

Best,
Alex
 
(DEEPLABCUT) C:\Users\90833\Downloads\alma-master>python ./alma.py
Traceback (most recent call last):
  File "./alma.py", line 2, in <module>
    from Panels import Start, AnalyzeStride, AnalyzeFootfall, RandomForest, PCA
  File "C:\Users\90833\Downloads\alma-master\Panels\RandomForest.py", line 3, in <module>
    from Functions import ConfigFunctions, DataAnalysisFunctions
  File "C:\Users\90833\Downloads\alma-master\Functions\DataAnalysisFunctions.py", line 7, in <module>
    import seaborn as sns
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\seaborn\__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\seaborn\rcmod.py", line 82, in <module>
    if LooseVersion(mpl.__version__) >= "3.0":
  File "C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\setuptools\_distutils\version.py", line 55, in __init__
    warnings.warn(
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

**Comment by sollan** [comment]
Hi Alex! Can you please try to reinstall following these steps (without using Anaconda and in a fresh environment with no previously installed packages, including DLC)? 

https://github.com/sollan/alma/issues/18#issuecomment-1147513572

Let me know if this helps :)

Best,
Annette

**Comment by wuwuqaz** [comment]
> Hi Alex! Can you please try to reinstall following these steps? As you are working on a Windows machine, some of these commands won't work and maybe you'll need to check the environment variables for your Python version. But in general, most importantly for the installation, please create a fresh environment with no previously installed packages, including DeepLabCut.
> 
> [#18 (comment)](https://github.com/sollan/alma/issues/18#issuecomment-1147513572)
> 
> Let me know if this works or if you need more help :)
> 
> Best, Annette

Hi Annette,

Thank you so much for your help. I am using windows. After installed python 3.8.5 without using virtual environment, it works.
really appreciate to your help : )

Best,
Alex
