### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by luofangcheng** [sollan/alma#21]
When I run ALMA, it has an issue with numpy. The numpy version is 1.22.4

<img width="973" alt="image" src="https://user-images.githubusercontent.com/112549604/189489792-0044866d-b6c8-47db-8b46-d35a5520fe6b.png">

**Comment by sollan** [comment]
Hi! There is most likely a conflict between your library versions. Please take a look at the instructions here - #18 and let me know if that helps.

Best,
Annette

**Comment by sollan** [comment]
Please get in touch again if you need additional support :)
