### ISSUE TITLE
Has this been tested on animals beside rodents?

### ISSUE THREAD

**Issue by Monnesee** [sollan/alma#22]
Hi, just curious about using this on fish and flies. Is there anything particularly specific to rodents? Thanks

**Comment by sollan** [comment]
Hi! This toolbox has only been tested on rodents, as it was designed for specific behavioral tests (kinematic analysis and ladder rung). If you’re interested in collecting and/or extracting bodypart coordinates from video data of other species, using deep learning, you could check out DeepLabCut (which is what we used for extracting the bodypart coordinates from videos, based on which we then created this toolbox for the data analysis) or other markerless (animal) bodypart tracking libraries for this purpose. 

I can also imagine having GUIs similar to what we have here, for additional species and their behavioral analysis. But so far, this is rodent-specific.
