### ISSUE TITLE
python package with conflicting dependency

### ISSUE THREAD

**Issue by xyp42eve** [sollan/alma#25]
Hey Alma developers/users,

Here a conflicting dependency with the latest version of packages is found in win10 python 3.8 version. 

The following two packages have to lower the version. 
Matplotlib 3.6.2->3.5.3
Seaborn 0.12.3 -> 0.11.1

Happy Analyzing and Thanks for the development team:) 
XQ

**Comment by sollan** [comment]
Thank you for pointing this out!
