### ISSUE TITLE
How to extract the variables/parameters associated with each principal component?

### ISSUE THREAD

**Issue by SIM0N-WU** [sollan/alma#33]
In the paper, it Is mentioned that you could calculate the "factor loadings" (Fig. 2), or extract the "key parameters clustering with PC1" (Fig. 5). I was wondering if this function was included in the toolbox? If not, would it be possible if you could provide a brief tutorial on how one could approach this? I am grateful for this toolbox as it has allowed me to easier access to machine learning analysis techniques like PCA and Random forest classification, tools that I could not use before.

**Comment by sollan** [comment]
Hi, sorry for the late reply! 

Not sure if you've found the solution yet, but we have actually included the PCA analysis function in the GUI (check out the [Wiki](https://github.com/sollan/alma/wiki/Kinematic-data-analysis) page or [source code](https://github.com/sollan/alma/blob/a3a1c0ea17d775523f84568dad8d57a6bcfe8193/Functions/DataAnalysisFunctions.py#L125)). As you can see the GUI option is based on `scikit-learn` and simply uses default values. But won't be hard to implement your own PCA with sklearn to try out different parameters, e.g. number of components. Feel free to use the source code from Alma as a starting point (especially if you're using output from the automated kinematic analysis, then the data preprocessing code from Alma can be reused to parse the input for the sklearn functions). 

You can find some sklearn tutorials for PCA here: https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

**Comment by SIM0N-WU** [comment]
Hi Sollan,

Thank you for the guidance. The sklearn tutorial link was helpful. I am not able to view the weighting the goes into each principal component! I think in the future, it would be useful to other researchers if a .csv file containing the parameter weights for each PC would automatically be exported as well!

Thanks a lot,
Simon
