### ISSUE TITLE
Metadata-generation-failed

### ISSUE THREAD

**Issue by NuriaAt** [sollan/alma#36]
Hi, 

Thank you for building this great toolbox! Unfortunately, I tried to install the requirements but I encounter with an error message: 'metadata-generation-failed'. I think it might be related to the numpy requirement. Could you help me with this? 

Thanks!

**Comment by sollan** [comment]
@NuriaAt 

Hello again,

I tested the dependencies with Python 3.10, as Python 3.8 (which has been the recommendation so far) will reach end of life next year. You can find the requirements for a Conda env [here](https://github.com/sollan/alma/blob/master/conda_env_python_3_10.yml) and try installing in a Python 3.10 environment. 

Hope that helps!

Annette

**Comment by NuriaAt** [comment]
Hi Anette,

Thanks so much. It works now in a Python 3.10 environment 😊
I have another question; would it be possible to change the tracking points somewhere in the config file? I usually perform my tracking labelling also the body and the tail.

Have a nice day,

Best,
Nuria
